name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-docker:
    runs-on: self-hosted
    container:
      image: xlemonx/arm-gnu-toolchain:13.3.1
      volumes:
        - builds:/builds
      options: --user 1000:1000
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          set-safe-directory: false

      - name: Init environment
        run: ./init-build.sh

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build 

      - name: Save binary file
        run: cp build/firmware.bin firmware.bin
      
      - name: Archive bianry files
        uses: actions/upload-artifact@v4
        with:
          name: Firmware bin
          path: build/firmware.bin
      - name: Archive bianry files
        uses: actions/upload-artifact@v4
        with:
          name: Firmware elf
          path: build/firmware.elf



  # deploy:
  #   needs: build
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Executable
  #         path: ${{ github.workspace }}/firmware.bin
