name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux] 
    steps:
      - name: Checkout code
        run: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build

      - name: Save binary file
        run: cp build/your_binary_file.bin ${{ github.workspace }}/your_binary_file.bin