name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.21'

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build

      - name: Save binary file
        run: cp build/your_binary_file.bin ${{ github.workspace }}/your_binary_file.bin