name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build 

      - name: Save binary file
        run: cp build/firmware.bin ${{ github.workspace }}/firmware.bin

  build-docker:
    runs-on: self-hosted
    container:
      image: xlemonx/arm-gnu-toolchain:13.3.1
      volumes:
        - builds:/builds
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build 

      - name: Save binary file
        run: cp build/firmware.bin firmware.bin


  deploy:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: ${{ github.workspace }}/firmware.bin
